#!/bin/bash
cd ${0%/*} || exit 1

. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions

runParallel()
{
  # local appArgs="-parallel"
  local appArgs="-parallel -fileHandler collated"
  local mpirun="mpirun"
  local appRun="$1"
  local nProcs=$(getNumberOfProcessors system/decomposeParDict)
  local appName="${appRun##*/}"
  local logFile="log.$appName"

  if [ -f "$logFile" ]
  then
    echo "$appName already run on $PWD: remove log file to re-run"
  else
    echo "Running $appRun ($nProcs processes) on $PWD"
    $mpirun -n $nProcs $appRun $appArgs </dev/null >> $logFile 2>&1
  fi
}

if [ -f pre-mesh.sh ]; then
    echo "Processing STL transformations..."
    sh pre-mesh.sh >> log.pre-mesh 2>&1
fi

if [ -f system/surfaceFeaturesDict ]; then
    runApplication surfaceFeatures
fi

runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication checkMesh


runApplication potentialFoam -writep

N_PROCS=$(getNumberOfProcessors system/decomposeParDict)

if [ "$N_PROCS" -gt 1 ]; then
  echo "Setting up parallel run for $N_PROCS cores..."
  # runApplication decomposePar
  runApplication decomposePar -force -fileHandler collated
  
  runParallel $(getApplication)
  
  echo "Starting parallel reconstruction..."
  rm -f merged.txt todo.txt
 
  foamListTimes > merged.txt
  foamListTimes -processor | grep -vFf merged.txt > todo.txt

  cat todo.txt | xargs -P 32 -n 1 reconstructPar -fileHandler collated -time
  
  rm -f merged.txt todo.txt
  
  # ==========================================================
  echo "Generating cell centres (C field) for all time steps..."
  runApplication postProcess -func writeCellCentres -fileHandler collated -time 0.00000
#   # ==========================================================
  echo "Cleaning up parallel folders..."
  rm -rf processor*  
  
else
  echo "Running in serial mode..."
  runApplication $(getApplication)
fi

echo "Allrun finished."